export default {
    "title" : [
        {
            "text": "京东2010年来TOP100贵金属商品词云",
            "x": "center",
            "top": 10
        }, {
            "text": "数据来源:smzdm",
            "borderWidth": 0,
            "textStyle": {
                "fontSize": 10,
                "fontWeight": "normal"
            },
            "x": 5,
            "y2": 0
        }, {
            "text": "©成都印钞有限公司 技术质量部",
            "borderColor": "#999",
            "borderWidth": 0,
            "textStyle": {
                "fontSize": 10,
                "fontWeight": "normal"
            },
            "x": "right",
            "y2": 3
        }
    ],
    "grid" : {
        "left": "5%",
        "right": "5%",
        "top": "8%",
        "bottom": "10%",
        "containLabel": true
    },
    "toolbox" : {
        "show": true,
        "feature": {
            "dataView": {
                "show": true,
                "readOnly": false
            },
            "restore": {
                "show": true
            },
            "saveAsImage": {
                "show": true
            }
        },
        "top": 10
    },
    "series" : {
        "type": "wordCloud",
        "sizeRange": [
            15, 120
        ],
        "rotationRange": [
            -90, 90
        ],
        "rotationStep": 1,
        "shape": "circle",
        "textStyle": {
            "normal": {}
        },
        "data": [
            {
                "name": "mao",
                "value": 6
            }, {
                "name": "七夕",
                "value": 2
            }, {
                "name": "七夕情人",
                "value": 2
            }, {
                "name": "七夕情人节",
                "value": 2
            }, {
                "name": "个性",
                "value": 4
            }, {
                "name": "串",
                "value": 5
            }, {
                "name": "串珠",
                "value": 2
            }, {
                "name": "之",
                "value": 2
            }, {
                "name": "人工",
                "value": 2
            }, {
                "name": "价",
                "value": 2
            }, {
                "name": "优雅",
                "value": 2
            }, {
                "name": "佛",
                "value": 3
            }, {
                "name": "佛珠",
                "value": 2
            }, {
                "name": "倾",
                "value": 2
            }, {
                "name": "八大",
                "value": 3
            }, {
                "name": "六字大明咒",
                "value": 3
            }, {
                "name": "创意",
                "value": 3
            }, {
                "name": "刻字",
                "value": 5
            }, {
                "name": "十二生肖",
                "value": 2
            }, {
                "name": "单个",
                "value": 2
            }, {
                "name": "单只",
                "value": 2
            }, {
                "name": "可",
                "value": 4
            }, {
                "name": "吉祥物",
                "value": 2
            }, {
                "name": "吊坠",
                "value": 13
            }, {
                "name": "后",
                "value": 5
            }, {
                "name": "周",
                "value": 8
            }, {
                "name": "周大福",
                "value": 7
            }, {
                "name": "周生生",
                "value": 8
            }, {
                "name": "命",
                "value": 2
            }, {
                "name": "品",
                "value": 2
            }, {
                "name": "品质",
                "value": 2
            }, {
                "name": "唯一",
                "value": 2
            }, {
                "name": "圈",
                "value": 2
            }, {
                "name": "复古",
                "value": 2
            }, {
                "name": "大小",
                "value": 2
            }, {
                "name": "大明咒",
                "value": 3
            }, {
                "name": "大福",
                "value": 8
            }, {
                "name": "天然",
                "value": 5
            }, {
                "name": "夹",
                "value": 2
            }, {
                "name": "女",
                "value": 23
            }, {
                "name": "女友",
                "value": 20
            }, {
                "name": "女士",
                "value": 12
            }, {
                "name": "女款",
                "value": 9
            }, {
                "name": "妈妈",
                "value": 5
            }, {
                "name": "子",
                "value": 2
            }, {
                "name": "守护神",
                "value": 3
            }, {
                "name": "定价",
                "value": 2
            }, {
                "name": "定做",
                "value": 2
            }, {
                "name": "对",
                "value": 5
            }, {
                "name": "对价",
                "value": 4
            }, {
                "name": "对戒",
                "value": 12
            }, {
                "name": "尾戒",
                "value": 5
            }, {
                "name": "属",
                "value": 3
            }, {
                "name": "工",
                "value": 11
            }, {
                "name": "开口",
                "value": 11
            }, {
                "name": "彩虹",
                "value": 3
            }, {
                "name": "心形",
                "value": 3
            }, {
                "name": "心心相印",
                "value": 2
            }, {
                "name": "心扉",
                "value": 3
            }, {
                "name": "恋",
                "value": 2
            }, {
                "name": "情人",
                "value": 2
            }, {
                "name": "情人节",
                "value": 12
            }, {
                "name": "情人节礼物",
                "value": 10
            }, {
                "name": "情侣",
                "value": 24
            }, {
                "name": "慕",
                "value": 2
            }, {
                "name": "戒",
                "value": 3
            }, {
                "name": "戒子",
                "value": 2
            }, {
                "name": "戒指",
                "value": 27
            }, {
                "name": "手",
                "value": 8
            }, {
                "name": "手环",
                "value": 2
            }, {
                "name": "手链",
                "value": 22
            }, {
                "name": "手镯",
                "value": 20
            }, {
                "name": "折",
                "value": 5
            }, {
                "name": "挂坠",
                "value": 2
            }, {
                "name": "指环",
                "value": 5
            }, {
                "name": "日韩",
                "value": 2
            }, {
                "name": "时尚",
                "value": 16
            }, {
                "name": "时尚饰品",
                "value": 7
            }, {
                "name": "星",
                "value": 3
            }, {
                "name": "晶",
                "value": 5
            }, {
                "name": "曜",
                "value": 2
            }, {
                "name": "月",
                "value": 2
            }, {
                "name": "本",
                "value": 2
            }, {
                "name": "本命佛",
                "value": 2
            }, {
                "name": "梦",
                "value": 2
            }, {
                "name": "款",
                "value": 16
            }, {
                "name": "母亲节",
                "value": 3
            }, {
                "name": "毛衣",
                "value": 2
            }, {
                "name": "气质",
                "value": 2
            }, {
                "name": "水晶",
                "value": 6
            }, {
                "name": "沉鱼落雁",
                "value": 2
            }, {
                "name": "满天星",
                "value": 11
            }, {
                "name": "潮男",
                "value": 2
            }, {
                "name": "炫",
                "value": 2
            }, {
                "name": "爱",
                "value": 4
            }, {
                "name": "爱人",
                "value": 3
            }, {
                "name": "版",
                "value": 2
            }, {
                "name": "狗",
                "value": 2
            }, {
                "name": "猪",
                "value": 2
            }, {
                "name": "玫瑰",
                "value": 2
            }, {
                "name": "玫瑰花",
                "value": 3
            }, {
                "name": "珍珠",
                "value": 2
            }, {
                "name": "瑞诺",
                "value": 5
            }, {
                "name": "生日",
                "value": 5
            }, {
                "name": "生日礼物",
                "value": 13
            }, {
                "name": "男",
                "value": 3
            }, {
                "name": "男友",
                "value": 2
            }, {
                "name": "男士",
                "value": 11
            }, {
                "name": "男女",
                "value": 15
            }, {
                "name": "男款",
                "value": 5
            }, {
                "name": "白色",
                "value": 2
            }, {
                "name": "白金",
                "value": 4
            }, {
                "name": "的",
                "value": 3
            }, {
                "name": "皇冠",
                "value": 3
            }, {
                "name": "眼",
                "value": 3
            }, {
                "name": "短款",
                "value": 3
            }, {
                "name": "石",
                "value": 2
            }, {
                "name": "石缘",
                "value": 2
            }, {
                "name": "礼品",
                "value": 2
            }, {
                "name": "礼物",
                "value": 18
            }, {
                "name": "礼盒",
                "value": 5
            }, {
                "name": "福",
                "value": 4
            }, {
                "name": "简约",
                "value": 8
            }, {
                "name": "粗",
                "value": 2
            }, {
                "name": "精选",
                "value": 3
            }, {
                "name": "紫",
                "value": 2
            }, {
                "name": "紫色",
                "value": 3
            }, {
                "name": "约",
                "value": 6
            }, {
                "name": "纪念币",
                "value": 2
            }, {
                "name": "纯银",
                "value": 5
            }, {
                "name": "结婚",
                "value": 3
            }, {
                "name": "缔",
                "value": 5
            }, {
                "name": "缘",
                "value": 2
            }, {
                "name": "美",
                "value": 2
            }, {
                "name": "老人",
                "value": 2
            }, {
                "name": "老婆",
                "value": 3
            }, {
                "name": "耳",
                "value": 4
            }, {
                "name": "耳环",
                "value": 8
            }, {
                "name": "耳钉",
                "value": 12
            }, {
                "name": "耳饰",
                "value": 3
            }, {
                "name": "至尊",
                "value": 4
            }, {
                "name": "节",
                "value": 2
            }, {
                "name": "节日",
                "value": 4
            }, {
                "name": "花",
                "value": 3
            }, {
                "name": "菩萨",
                "value": 2
            }, {
                "name": "菱",
                "value": 4
            }, {
                "name": "计价",
                "value": 11
            }, {
                "name": "证书",
                "value": 10
            }, {
                "name": "调节",
                "value": 3
            }, {
                "name": "豪",
                "value": 2
            }, {
                "name": "貔貅",
                "value": 3
            }, {
                "name": "费",
                "value": 11
            }, {
                "name": "足金",
                "value": 18
            }, {
                "name": "足银",
                "value": 16
            }, {
                "name": "转运珠",
                "value": 4
            }, {
                "name": "送",
                "value": 33
            }, {
                "name": "部落",
                "value": 2
            }, {
                "name": "配",
                "value": 6
            }, {
                "name": "配送",
                "value": 2
            }, {
                "name": "配饰",
                "value": 5
            }, {
                "name": "金",
                "value": 2
            }, {
                "name": "金玫瑰",
                "value": 2
            }, {
                "name": "钞",
                "value": 2
            }, {
                "name": "铂金",
                "value": 3
            }, {
                "name": "银",
                "value": 56
            }, {
                "name": "银耳",
                "value": 3
            }, {
                "name": "银饰",
                "value": 5
            }, {
                "name": "银饰品",
                "value": 27
            }, {
                "name": "链",
                "value": 16
            }, {
                "name": "锁骨",
                "value": 8
            }, {
                "name": "锆石",
                "value": 2
            }, {
                "name": "镯子",
                "value": 8
            }, {
                "name": "长",
                "value": 2
            }, {
                "name": "闪",
                "value": 2
            }, {
                "name": "闺蜜",
                "value": 2
            }, {
                "name": "阿弥陀佛",
                "value": 2
            }, {
                "name": "附",
                "value": 3
            }, {
                "name": "霸气",
                "value": 3
            }, {
                "name": "韩版",
                "value": 15
            }, {
                "name": "项链",
                "value": 31
            }, {
                "name": "风",
                "value": 2
            }, {
                "name": "饰",
                "value": 2
            }, {
                "name": "饰品",
                "value": 15
            }, {
                "name": "首饰",
                "value": 15
            }, {
                "name": "鸡",
                "value": 2
            }, {
                "name": "黄金",
                "value": 20
            }, {
                "name": "黑曜石",
                "value": 8
            }, {
                "name": "黑色",
                "value": 2
            }, {
                "name": "龙凤",
                "value": 3
            }
        ]
    }
};
