let option = {
    "title": [
        {
            "text": "金币总公司销售额百万以上商品名称词云",
            "x": "center",
            "top": 10
        }, {
            "text": "数据来源:smzdm",
            "borderWidth": 0,
            "textStyle": {
                "fontSize": 10,
                "fontWeight": "normal"
            },
            "x": 5,
            "y2": 0
        }, {
            "text": "©成都印钞有限公司 技术质量部",
            "borderColor": "#999",
            "borderWidth": 0,
            "textStyle": {
                "fontSize": 10,
                "fontWeight": "normal"
            },
            "x": "right",
            "y2": 3
        }
    ],
    "grid": {
        "left": "5%",
        "right": "5%",
        "top": "8%",
        "bottom": "10%",
        "containLabel": true
    },
    "toolbox": {
        "show": true,
        "feature": {
            "dataView": {
                "show": true,
                "readOnly": false
            },
            "restore": {
                "show": true
            },
            "saveAsImage": {
                "show": true
            }
        },
        "top": 10
    },
    "series": {
        "type": "wordCloud",
        "sizeRange": [
            15, 120
        ],
        "rotationRange": [
            -90, 90
        ],
        "rotationStep": 1,
        "shape": "circle",
        "textStyle": {
            "normal": {}
        },
        "data": [
            {
                "name": "丁酉",
                "value": 7
            }, {
                "name": "世界遗产",
                "value": 2
            }, {
                "name": "丙申",
                "value": 8
            }, {
                "name": "业",
                "value": 1
            }, {
                "name": "中国",
                "value": 27
            }, {
                "name": "中国熊猫",
                "value": 3
            }, {
                "name": "五福",
                "value": 1
            }, {
                "name": "会馆",
                "value": 1
            }, {
                "name": "全套",
                "value": 2
            }, {
                "name": "制",
                "value": 17
            }, {
                "name": "加",
                "value": 2
            }, {
                "name": "北京",
                "value": 1
            }, {
                "name": "北京银行",
                "value": 1
            }, {
                "name": "博览会",
                "value": 1
            }, {
                "name": "发行",
                "value": 3
            }, {
                "name": "古代",
                "value": 1
            }, {
                "name": "吉祥",
                "value": 4
            }, {
                "name": "同心",
                "value": 1
            }, {
                "name": "国际",
                "value": 2
            }, {
                "name": "圆形",
                "value": 4
            }, {
                "name": "大",
                "value": 4
            }, {
                "name": "大足石刻",
                "value": 1
            }, {
                "name": "套",
                "value": 13
            }, {
                "name": "套装",
                "value": 8
            }, {
                "name": "孔庙",
                "value": 1
            }, {
                "name": "孔府",
                "value": 1
            }, {
                "name": "孔林",
                "value": 1
            }, {
                "name": "字",
                "value": 2
            }, {
                "name": "宁波",
                "value": 1
            }, {
                "name": "宁波钱业会馆",
                "value": 1
            }, {
                "name": "家",
                "value": 1
            }, {
                "name": "寿",
                "value": 1
            }, {
                "name": "封装",
                "value": 43
            }, {
                "name": "币",
                "value": 16
            }, {
                "name": "年年有余",
                "value": 1
            }, {
                "name": "并蒂",
                "value": 1
            }, {
                "name": "彩色",
                "value": 5
            }, {
                "name": "戏剧",
                "value": 1
            }, {
                "name": "戏剧家",
                "value": 1
            }, {
                "name": "成立",
                "value": 2
            }, {
                "name": "扇形",
                "value": 4
            }, {
                "name": "护照",
                "value": 1
            }, {
                "name": "拱",
                "value": 1
            }, {
                "name": "散装",
                "value": 2
            }, {
                "name": "文化",
                "value": 4
            }, {
                "name": "普",
                "value": 17
            }, {
                "name": "曲阜",
                "value": 1
            }, {
                "name": "曲阜孔庙",
                "value": 1
            }, {
                "name": "曲阜孔庙孔林孔府封装金银套",
                "value": 1
            }, {
                "name": "汤显祖",
                "value": 1
            }, {
                "name": "熊猫",
                "value": 22
            }, {
                "name": "熊猫金币",
                "value": 3
            }, {
                "name": "版",
                "value": 17
            }, {
                "name": "猴",
                "value": 8
            }, {
                "name": "瓜瓞绵绵",
                "value": 1
            }, {
                "name": "盒装",
                "value": 2
            }, {
                "name": "精制",
                "value": 9
            }, {
                "name": "纪念币",
                "value": 9
            }, {
                "name": "设立",
                "value": 1
            }, {
                "name": "贺岁",
                "value": 2
            }, {
                "name": "金属",
                "value": 1
            }, {
                "name": "金币",
                "value": 18
            }, {
                "name": "金银",
                "value": 16
            }, {
                "name": "金银币",
                "value": 3
            }, {
                "name": "金银纪念币",
                "value": 5
            }, {
                "name": "钱",
                "value": 1
            }, {
                "name": "钱业会馆",
                "value": 1
            }, {
                "name": "钱币",
                "value": 2
            }, {
                "name": "银币",
                "value": 11
            }, {
                "name": "银行",
                "value": 1
            }, {
                "name": "银质",
                "value": 1
            }, {
                "name": "长方形",
                "value": 2
            }, {
                "name": "门票",
                "value": 1
            }, {
                "name": "青岛",
                "value": 1
            }, {
                "name": "青岛银行",
                "value": 1
            }, {
                "name": "鸡",
                "value": 7
            }
        ]
    }
};
export default option;